# Generated by Django 5.0.1 on 2024-01-22 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BS', 'Balance Sheet'), ('IS', 'Income Statement'), ('CF', 'Cash Flow Statement')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatementLineSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.financialstatement')),
                ('financial_statement_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.financialstatementline')),
            ],
        ),
    ]
