# Generated by Django 5.0.1 on 2024-01-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementtype',
            name='type',
            field=models.CharField(choices=[('IS', 'Income Statement'), ('BS', 'Balance Sheet'), ('CF', 'Cash Flow Statement')], max_length=2),
        ),
    ]
