# Generated by Django 5.0.1 on 2024-01-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_financialstatementtype_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialStatementLineSequence',
        ),
    ]
